export default [
  {
    figmaLabel: 'Alert',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Accordion',
    storybookLabel: 'Accordion',
    storybookLabelLink: 'Accordion',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Button',
    storybookLabel: 'Button',
    storybookLabelLink: 'Button',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'ButtonGroup',
    storybookLabelLink: 'ButtonGroup',
    where: 'storybook',
    state: 'same',
    coment: 'Not needed on Fimga',
  },
  {
    figmaLabel: 'ButtonIcon',
    storybookLabel: 'ButtonIcon',
    storybookLabelLink: 'ButtonIcon',
    where: 'both',
    state: 'different',
    coment: 'Different variants, sizes, floating...',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'Carousel',
    storybookLabelLink: '',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'ChartColumn',
    storybookLabelLink: '',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'ChartLine',
    storybookLabelLink: '',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Collapse',
    storybookLabel: '',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Checkbox',
    storybookLabel: 'Check',
    storybookLabelLink: 'Check',
    where: 'both',
    state: 'same',
    coment: 'In Figma we have indeterminate and error but is not needed now',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'CheckGroup',
    storybookLabelLink: 'CheckGroup',
    where: 'storybook',
    state: 'same',
    coment: 'Not needed on Figma',
  },
  {
    figmaLabel: 'Divider',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Radio',
    storybookLabel: 'Check',
    storybookLabelLink: 'Check',
    where: 'both',
    state: 'same',
    coment: 'In storybook is part of the checkbox component',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'Device',
    storybookLabelLink: 'Device',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Empty state',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Field',
    storybookLabel: 'Field',
    storybookLabelLink: 'Field',
    where: 'both',
    state: 'different',
    coment: 'Is not necessary',
  },
  {
    figmaLabel: 'Input',
    storybookLabel: 'Input',
    storybookLabelLink: 'Input',
    where: 'both',
    state: 'different',
    coment: 'Add icon and separate from field',
  },
  {
    figmaLabel: 'Select',
    storybookLabel: 'Select',
    storybookLabelLink: 'Select',
    where: 'both',
    state: 'different',
    coment: 'Add tag and separate from field',
  },
  {
    figmaLabel: 'Icons',
    storybookLabel: 'Icon',
    storybookLabelLink: 'Icon',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Issue',
    storybookLabel: 'IssueDropDown',
    storybookLabelLink: 'IssueDropDown',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Keyword',
    storybookLabel: 'Keyword',
    storybookLabelLink: 'Keyword',
    where: 'both',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'Kpi',
    storybookLabelLink: 'Kpi',
    where: 'storybook',
    state: 'different',
    coment: 'Metric and KPI',
  },
  {
    figmaLabel: 'Level',
    storybookLabel: 'Level',
    storybookLabelLink: 'Level',
    where: 'both',
    state: 'same',
    coment: 'There are more sizes on Storybook but are not necessary now',
  },
  {
    figmaLabel: 'Metric',
    storybookLabel: 'Metric',
    storybookLabelLink: 'Metric',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Modal',
    storybookLabel: 'Modal',
    storybookLabelLink: 'Modal',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'NavWP',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'NavApp & OptionApp & NavAccount',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'both',
    state: 'different',
    coment: 'Menu + MenuOption',
  },
  {
    figmaLabel: 'NavSide & OptionSide',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'both',
    state: 'different',
    coment: '-> Navigation',
  },
  {
    figmaLabel: 'Page',
    storybookLabel: 'Page',
    storybookLabelLink: 'Page',
    where: 'both',
    state: 'same',
    coment: 'Will need states',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'Panel',
    storybookLabelLink: 'Panel',
    where: 'storybook',
    state: 'different',
    coment: 'Not needed on Figma',
  },
  {
    figmaLabel: 'Pagination',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Progress Bar',
    storybookLabel: 'ProgessBar',
    storybookLabelLink: 'ProgessBar',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'ProgressCircle',
    storybookLabelLink: 'ProgressCircle',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Score',
    storybookLabel: 'Score',
    storybookLabelLink: 'Score',
    where: 'both',
    state: 'different',
    coment: 'Style',
  },
  {
    figmaLabel: 'Search',
    storybookLabel: 'SearchField',
    storybookLabelLink: 'SearchField',
    where: 'both',
    state: 'different',
    coment: 'Changes needed on Storybook',
  },
  {
    figmaLabel: 'Section Header',
    storybookLabel: 'Section',
    storybookLabelLink: 'Section',
    where: 'both',
    state: 'same',
    coment: 'It will need a buttonicon option on Storybook (not needed now)',
  },
  {
    figmaLabel: 'Segment',
    storybookLabel: 'Segment',
    storybookLabelLink: 'Segment',
    where: 'both',
    state: 'different',
    coment: 'It will need one state for selected and hover. Error on focus',
  },
  {
    figmaLabel: 'SpeedMeter',
    storybookLabel: 'SpeedMeter',
    storybookLabelLink: 'SpeedMeter',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Spinner',
    storybookLabel: 'Spinner',
    storybookLabelLink: 'Spinner',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Stepper',
    storybookLabel: '-',
    storybookLabelLink: '',
    where: 'figma',
    state: 'different',
    coment: 'Remove form Figma',
  },
  {
    figmaLabel: 'Switch',
    storybookLabel: 'Switch',
    storybookLabelLink: 'Switch',
    where: 'both',
    state: 'same',
    coment: 'Label and description',
  },
  {
    figmaLabel: 'Table',
    storybookLabel: 'Table',
    storybookLabelLink: 'Table',
    where: 'both',
    state: 'different',
    coment: 'Cells on Figma',
  },
  {
    figmaLabel: 'Tabs',
    storybookLabel: 'Tabs',
    storybookLabelLink: 'Tabs',
    where: 'both',
    state: 'different',
    coment: 'Will need more states. Review use',
  },
  {
    figmaLabel: 'Tag',
    storybookLabel: 'Tag',
    storybookLabelLink: 'Tag',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'Task',
    storybookLabelLink: 'Task',
    where: 'storybook',
    state: 'different',
    coment: 'Different between task and issue',
  },
  {
    figmaLabel: '-',
    storybookLabel: 'TaskGroup',
    storybookLabelLink: 'TaskGroup',
    where: 'storybook',
    state: 'different',
    coment: '',
  },
  {
    figmaLabel: 'Thumbnail',
    storybookLabel: 'Thumbnail',
    storybookLabelLink: 'Thumbnail',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'Tooltip',
    storybookLabel: 'Tooltip',
    storybookLabelLink: 'Tooltip',
    where: 'both',
    state: 'same',
    coment: '',
  },
  {
    figmaLabel: 'TreeList Element',
    storybookLabel: 'TreeList',
    storybookLabelLink: 'TreeList',
    where: 'both',
    state: 'different',
    coment: 'states and components inside',
  },
]
